### ISSUE TITLE
SQL - "Foreign key constraint is incorrectly formed"

### ISSUE THREAD

**Issue by MIAgimir** [overextended/ox_mdt#1]
I received this issue when trying to add the sql files. It would get to line 32 where it creates the table 'ox_mdt_reports_criminals and comes up with this error. I'm not familiar with the error message or if anyone else has experienced this issue before.

![image](https://github.com/overextended/ox_mdt/assets/116332087/d0f36780-0b33-41e0-828c-5c78775a945d)

**Comment by LukeWasTakenn** [comment]
What MariaDB version?

**Comment by MIAgimir** [comment]
Using version 11.1.0

**Comment by LukeWasTakenn** [comment]
I'm on 10.11.2 but it should still be fine, I did try rerunning all the queries and it does work as expected, not sure 🤷

**Comment by MIAgimir** [comment]
On line 42:
```FOREIGN KEY (`stateid`) REFERENCES `characters` (`stateid`)```

My characters table doesn't have stateid in it. Is that something I'm missing or am I reading the sql file wrong?

**Comment by LukeWasTakenn** [comment]
make sure you are on latest ox_core I guess

**Comment by FjamZoo** [comment]
> FOREIGN KEY (`stateid`) REFERENCES `characters` (`stateid`)

Ain't this supposed to be stateId?

https://github.com/overextended/ox_core/blob/main/sql/install.sql#L34

**Comment by FjamZoo** [comment]
nvm I ran the sql just fine

**Comment by LukeWasTakenn** [comment]
> Ain't this supposed to be stateId?

Queries are case insensitive

**Comment by MIAgimir** [comment]
I am going to see about a fresh install on ox_core and my DB to see if that works

**Comment by MIAgimir** [comment]
Not sure what the issue was, but I did a fresh install of server / db from scratch and the sql ran normally, so I think it's fine.
