### ISSUE TITLE
[Suggestion] Ability to update charges from the front-end

### ISSUE THREAD

**Issue by xXJamieXx** [overextended/ox_mdt#13]
Would it be possible to allow those with the correct permissions to be able to add, remove and modify charges from the front-end so that they can be easily updated?

Perhaps extra buttons that show on the charges page if you have the correct permissions. If adding a charge it brings up a modal with all the required information for a charge to be filled in. If modifying it brings up the same modal but with the inputs pre-filled out with the existing information. If removing then it would delete the charge, an added bonus would be if it had a confirmation so it takes 2 clicks instead of 1.

Thanks :)

**Comment by LukeWasTakenn** [comment]
See #12,

I am yet to hear *good* reason to have this accessible in the UI rather than just letting the devs add/remove/edit them in the database.
