### ISSUE TITLE
[Suggestion] Vehicles page

### ISSUE THREAD

**Issue by xXJamieXx** [overextended/ox_mdt#14]
A vehicles page to be able to search for registered vehicles by plate. It would display information about the vehicle like the registered owner, make, model and color.

**Comment by LukeWasTakenn** [comment]
You'll be able to search for vehicle license plates in the profiles and get the profile the vehicle belongs to that way, I don't really see the point of making a whole separate page just to show the color of the vehicle? 🤔 

The space would be quite difficult to fill up and make sense of.

**Comment by xXJamieXx** [comment]
Ah ok thats a smart way to do it and makes sense thanks
