### ISSUE TITLE
Can't attach to call after one is completed

### ISSUE THREAD

**Issue by xXJamieXx** [overextended/ox_mdt#8]
When trying to attach to a second call after one is completed it doesn't attach the unit. Through debugging I found it was returning the call ID of the completed call and not the call I'm trying to attach to.

Reproduction steps:
1. Create a call
2. Attach unit to call
3. Mark call completed while attached
4. Create second call
5. Try to attach same unit to second call

https://github.com/overextended/ox_mdt/assets/11248045/b8d9be01-a6f6-45d3-b773-5413f7e61efc

**Comment by Archangelza1** [comment]
This is still a work in progress and should not be used in a productionized(Live server) instance, So they might be aware of this already. Thanks for reporting it though :)

**Comment by LukeWasTakenn** [comment]
It's not returning the ID of the debugged call, it's turning the activeCalls object into an array the call id of 0 is gotten rid of 🤔
